on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_KEY }}
          port: 22  # Cambia si tu servidor usa otro puerto
          source: "."  # Archivos a copiar
          target: "/var/www/bcsxplora/html"  # Ruta en el servidor
          overwrite: true
          rm: true
